//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_zds
    {
        public string zd_typename { get; set; }
        public string zd_type { get; set; }
        public string zd_id { get; set; }
        public string zd_name { get; set; }
        public int zd_seq { get; set; }
        public int status { get; set; }
        public string remark { get; set; }
        public string parentid { get; set; }
    }
}
