//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bj_part
    {
        public int id { get; set; }
        public Nullable<int> sbdl { get; set; }
        public Nullable<int> sbmc { get; set; }
        public Nullable<int> sbxl { get; set; }
        public string objcode { get; set; }
        public string objname { get; set; }
        public string cdepcode { get; set; }
        public string cdepname { get; set; }
        public string owndepcode { get; set; }
        public string owndepname { get; set; }
        public string matdepcode { get; set; }
        public string matdepname { get; set; }
        public string material { get; set; }
        public string conperson { get; set; }
        public string telephone { get; set; }
        public string mobile { get; set; }
        public string ownbgcode { get; set; }
        public string objpos { get; set; }
        public string objstate { get; set; }
        public string usestate { get; set; }
        public string crdate { get; set; }
        public string chdate { get; set; }
        public string datasource { get; set; }
        public string cdinatex { get; set; }
        public string cdinatey { get; set; }
        public string remark { get; set; }
    }
}
