//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_yjdws
    {
        public case_yjdws()
        {
            this.case_casesources = new HashSet<case_casesources>();
        }
    
        public int yjdwid { get; set; }
        public string yjdwname { get; set; }
    
        public virtual ICollection<case_casesources> case_casesources { get; set; }
    }
}
