//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_wtajs
    {
        public int wtid { get; set; }
        public string car_num { get; set; }
        public string car_type { get; set; }
        public string processstatus { get; set; }
        public Nullable<System.DateTime> wt_time { get; set; }
        public string wt_address { get; set; }
        public string wfxw { get; set; }
        public string cfjdsh { get; set; }
        public string cjdw { get; set; }
        public Nullable<int> cjr { get; set; }
        public string dsr { get; set; }
        public string dsr_phone { get; set; }
        public string dsr_address { get; set; }
        public string jdr { get; set; }
        public Nullable<System.DateTime> jdsj { get; set; }
        public Nullable<int> shr { get; set; }
        public Nullable<System.DateTime> shsj { get; set; }
        public string zfreason { get; set; }
        public string datastatus { get; set; }
        public string cldw { get; set; }
        public Nullable<double> fkje { get; set; }
        public string fphm { get; set; }
        public string processuser { get; set; }
        public Nullable<System.DateTime> processtime { get; set; }
        public string jsr { get; set; }
        public Nullable<System.DateTime> jssj { get; set; }
        public Nullable<int> isphone { get; set; }
        public Nullable<int> reportuserid { get; set; }
        public Nullable<System.DateTime> reporttime { get; set; }
        public Nullable<double> x84 { get; set; }
        public Nullable<double> y84 { get; set; }
        public Nullable<double> x2000 { get; set; }
        public Nullable<double> y2000 { get; set; }
        public Nullable<int> unitid { get; set; }
    }
}
