//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_workflowspecificactivitys
    {
        public case_workflowspecificactivitys()
        {
            this.doc_wfsas = new HashSet<doc_wfsas>();
            this.case_workflowspecificusers = new HashSet<case_workflowspecificusers>();
        }
    
        public string wfsaid { get; set; }
        public string wfsid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> dealuserid { get; set; }
        public Nullable<System.DateTime> dealtime { get; set; }
        public string wfdid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> stime { get; set; }
        public Nullable<System.DateTime> etime { get; set; }
    
        public virtual case_workflowdetails case_workflowdetails { get; set; }
        public virtual ICollection<doc_wfsas> doc_wfsas { get; set; }
        public virtual ICollection<case_workflowspecificusers> case_workflowspecificusers { get; set; }
        public virtual case_workflowspecifics case_workflowspecifics { get; set; }
    }
}
