//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_leadersupervises
    {
        public int supid { get; set; }
        public Nullable<int> caseid { get; set; }
        public string workflowid { get; set; }
        public Nullable<int> userid { get; set; }
        public string supopinion { get; set; }
        public Nullable<System.DateTime> suptime { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
