//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_workflowdetails
    {
        public case_workflowdetails()
        {
            this.doc_wfdddrs = new HashSet<doc_wfdddrs>();
            this.case_workflowspecificactivitys = new HashSet<case_workflowspecificactivitys>();
        }
    
        public string wfdid { get; set; }
        public string wfid { get; set; }
        public Nullable<int> phaseid { get; set; }
        public string wfdname { get; set; }
        public string nextid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> seqnum { get; set; }
        public string nextunitid { get; set; }
        public string nextroleid { get; set; }
    
        public virtual case_phases case_phases { get; set; }
        public virtual ICollection<doc_wfdddrs> doc_wfdddrs { get; set; }
        public virtual ICollection<case_workflowspecificactivitys> case_workflowspecificactivitys { get; set; }
    }
}
