//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_cases
    {
        public int caseid { get; set; }
        public string casebh { get; set; }
        public string casetypeid { get; set; }
        public string casename { get; set; }
        public string casesourceid { get; set; }
        public string qlsxid { get; set; }
        public string qlsx { get; set; }
        public string casereason { get; set; }
        public string fromcasesource { get; set; }
        public string caseaddress { get; set; }
        public System.DateTime sitedatetime { get; set; }
        public string geographical84 { get; set; }
        public string geographical2000 { get; set; }
        public string persontype { get; set; }
        public string p_name { get; set; }
        public string p_sex { get; set; }
        public string p_cardtype { get; set; }
        public string p_cardnum { get; set; }
        public string f_name { get; set; }
        public string f_dbr { get; set; }
        public string f_cardtype { get; set; }
        public string f_card { get; set; }
        public string f_wtr { get; set; }
        public string f_cardnum { get; set; }
        public string contactphone { get; set; }
        public string contactaddress { get; set; }
        public string flfg { get; set; }
        public string clyj { get; set; }
        public string wfqx { get; set; }
        public string cf { get; set; }
        public Nullable<double> zdmj { get; set; }
        public Nullable<double> gdmj { get; set; }
        public Nullable<double> gtjzmj { get; set; }
        public Nullable<double> ghjzmj { get; set; }
        public string casecontent { get; set; }
        public System.DateTime createtime { get; set; }
        public int createuserid { get; set; }
        public Nullable<int> sszd { get; set; }
        public Nullable<int> ssxbzd { get; set; }
        public Nullable<int> zbuserid { get; set; }
        public Nullable<int> xbuserid { get; set; }
        public Nullable<int> tzcsid { get; set; }
        public Nullable<int> issave { get; set; }
    }
}
