//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_workflowspecifics
    {
        public case_workflowspecifics()
        {
            this.case_workflowspecificactivitys = new HashSet<case_workflowspecificactivitys>();
        }
    
        public string wfsid { get; set; }
        public string wfid { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> status { get; set; }
        public string wfsname { get; set; }
        public string currentwfsaid { get; set; }
        public Nullable<int> filestatus { get; set; }
        public Nullable<int> casetype { get; set; }
        public Nullable<int> casesourceid { get; set; }
        public string casereason { get; set; }
        public string casemode { get; set; }
        public string contact { get; set; }
        public string contactphone { get; set; }
        public string address { get; set; }
        public string casetypeid { get; set; }
        public string casebh { get; set; }
        public string cswfsid { get; set; }
        public Nullable<int> caseid { get; set; }
        public string casestatus { get; set; }
    
        public virtual ICollection<case_workflowspecificactivitys> case_workflowspecificactivitys { get; set; }
    }
}
