//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_casesources
    {
        public int caseid { get; set; }
        public Nullable<int> sourceid { get; set; }
        public string contact { get; set; }
        public string contactphone { get; set; }
        public string contactaddress { get; set; }
        public string wfxwfsdz { get; set; }
        public string cluecontent { get; set; }
        public string processopinion { get; set; }
        public string notetaker { get; set; }
        public System.DateTime notetime { get; set; }
        public Nullable<int> sfla { get; set; }
        public Nullable<int> casetype { get; set; }
        public Nullable<int> sfbyla { get; set; }
        public Nullable<int> sfzc { get; set; }
        public Nullable<int> sfyj { get; set; }
        public Nullable<int> yjdwid { get; set; }
        public System.DateTime createtime { get; set; }
        public int createuserid { get; set; }
        public string casetypename { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> lastatus { get; set; }
    
        public virtual case_sources case_sources { get; set; }
        public virtual case_yjdws case_yjdws { get; set; }
    }
}
