//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_workflowspecificusers
    {
        public string wfsuid { get; set; }
        public Nullable<int> userid { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> dealtime { get; set; }
        public Nullable<int> status { get; set; }
        public string wfsaid { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> ismainuser { get; set; }
        public string remark { get; set; }
    
        public virtual case_workflowspecificactivitys case_workflowspecificactivitys { get; set; }
    }
}
