//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_SmsSent_2
    {
        public int ID { get; set; }
        public string MessageID { get; set; }
        public string MessageContent { get; set; }
        public string ExtendCode { get; set; }
        public string DestinationAddress { get; set; }
        public int SendType { get; set; }
        public System.DateTime SendTime { get; set; }
        public Nullable<int> IsWapPush { get; set; }
        public string WapUrl { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
