//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_wfdddrs
    {
        public int dwdid { get; set; }
        public Nullable<int> ddid { get; set; }
        public string wfdid { get; set; }
        public int isrequired { get; set; }
        public int seq { get; set; }
        public int status { get; set; }
    
        public virtual case_workflowdetails case_workflowdetails { get; set; }
        public virtual doc_definitions doc_definitions { get; set; }
    }
}
