//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDS_POWER
    {
        public string POWERID { get; set; }
        public string CODE { get; set; }
        public string POWERVERVISON { get; set; }
        public string POWERNAME { get; set; }
        public string DEPTKEY { get; set; }
        public string PUNISHTYPECODE { get; set; }
        public string JOIN_MODE { get; set; }
        public string OFFICEADDR { get; set; }
        public string PROMISE_DAY { get; set; }
        public string LAWLIMIT_DAY { get; set; }
        public string TELEPHONE { get; set; }
        public string CONTACT { get; set; }
        public string DUTYLEADER { get; set; }
        public string DUTYEOFFICE { get; set; }
        public string BODYIMPLEMENT { get; set; }
        public string BODYADDR { get; set; }
        public string REMARK { get; set; }
        public string SENDTIME { get; set; }
        public string FLAG { get; set; }
        public string AREACODE { get; set; }
        public string DATAVERVISON { get; set; }
        public string EXTEND_1 { get; set; }
        public string EXTEND_2 { get; set; }
        public string GETTIME { get; set; }
    }
}
