//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class fi_cameras
    {
        public string cameraid { get; set; }
        public string unitid { get; set; }
        public int cameratypeid { get; set; }
        public string cameraname { get; set; }
        public string parameter { get; set; }
        public Nullable<int> isonline { get; set; }
        public Nullable<double> x84 { get; set; }
        public Nullable<double> y84 { get; set; }
        public Nullable<double> x2000 { get; set; }
        public Nullable<double> y2000 { get; set; }
        public Nullable<int> seq { get; set; }
        public int logintype { get; set; }
    }
}
