//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<base_menus> base_menus { get; set; }
        public DbSet<base_permissionmenus> base_permissionmenus { get; set; }
        public DbSet<base_permissions> base_permissions { get; set; }
        public DbSet<base_rolepermissions> base_rolepermissions { get; set; }
        public DbSet<base_roles> base_roles { get; set; }
        public DbSet<base_units> base_units { get; set; }
        public DbSet<base_unittypes> base_unittypes { get; set; }
        public DbSet<base_userroles> base_userroles { get; set; }
        public DbSet<base_users> base_users { get; set; }
        public DbSet<base_usertypes> base_usertypes { get; set; }
        public DbSet<base_zds> base_zds { get; set; }
        public DbSet<case_cases> case_cases { get; set; }
        public DbSet<case_casesources> case_casesources { get; set; }
        public DbSet<case_phases> case_phases { get; set; }
        public DbSet<case_prescriptions> case_prescriptions { get; set; }
        public DbSet<case_simplecases> case_simplecases { get; set; }
        public DbSet<case_sources> case_sources { get; set; }
        public DbSet<case_workflowdetails> case_workflowdetails { get; set; }
        public DbSet<case_workflowspecificactivitys> case_workflowspecificactivitys { get; set; }
        public DbSet<case_workflowspecifics> case_workflowspecifics { get; set; }
        public DbSet<case_workflowspecificusers> case_workflowspecificusers { get; set; }
        public DbSet<case_wtajs> case_wtajs { get; set; }
        public DbSet<case_wtfiles> case_wtfiles { get; set; }
        public DbSet<case_yjdws> case_yjdws { get; set; }
        public DbSet<case_zds> case_zds { get; set; }
        public DbSet<doc_definitions> doc_definitions { get; set; }
        public DbSet<doc_wfdddrs> doc_wfdddrs { get; set; }
        public DbSet<doc_wfsas> doc_wfsas { get; set; }
        public DbSet<fi_camera_units> fi_camera_units { get; set; }
        public DbSet<fi_cameras> fi_cameras { get; set; }
        public DbSet<fi_cameratypes> fi_cameratypes { get; set; }
        public DbSet<fi_ovafiles> fi_ovafiles { get; set; }
        public DbSet<fi_uvas> fi_uvas { get; set; }
        public DbSet<mapelementcategory> mapelementcategories { get; set; }
        public DbSet<phone_version> phone_version { get; set; }
        public DbSet<qw_cars> qw_cars { get; set; }
        public DbSet<qw_cartasks> qw_cartasks { get; set; }
        public DbSet<qw_patrolareas> qw_patrolareas { get; set; }
        public DbSet<qw_patrollogs> qw_patrollogs { get; set; }
        public DbSet<qw_signinareas> qw_signinareas { get; set; }
        public DbSet<qw_userhistorypositions> qw_userhistorypositions { get; set; }
        public DbSet<qw_userlastpositions> qw_userlastpositions { get; set; }
        public DbSet<qw_usersignins> qw_usersignins { get; set; }
        public DbSet<qw_usertasks> qw_usertasks { get; set; }
        public DbSet<qw_zds> qw_zds { get; set; }
        public DbSet<sm_citizenservices> sm_citizenservices { get; set; }
        public DbSet<sm_classes> sm_classes { get; set; }
        public DbSet<sm_consultations> sm_consultations { get; set; }
        public DbSet<sm_sources> sm_sources { get; set; }
        public DbSet<sm_specialrectifications> sm_specialrectifications { get; set; }
        public DbSet<sm_visits> sm_visits { get; set; }
        public DbSet<systemconfig> systemconfigs { get; set; }
        public DbSet<tz_files> tz_files { get; set; }
        public DbSet<tz_registers> tz_registers { get; set; }
        public DbSet<tz_taskclasses> tz_taskclasses { get; set; }
        public DbSet<tz_tztasks> tz_tztasks { get; set; }
        public DbSet<wf_workflowdetails> wf_workflowdetails { get; set; }
        public DbSet<wf_workflows> wf_workflows { get; set; }
        public DbSet<wf_workflowspecificactivitys> wf_workflowspecificactivitys { get; set; }
        public DbSet<wf_workflowspecifics> wf_workflowspecifics { get; set; }
        public DbSet<wf_workflowspecificuserfiles> wf_workflowspecificuserfiles { get; set; }
        public DbSet<wf_workflowspecificusers> wf_workflowspecificusers { get; set; }
        public DbSet<wj_cqxms> wj_cqxms { get; set; }
        public DbSet<wj_files> wj_files { get; set; }
        public DbSet<wj_wzjzs> wj_wzjzs { get; set; }
        public DbSet<xz_licensings> xz_licensings { get; set; }
        public DbSet<xz_threebags> xz_threebags { get; set; }
        public DbSet<xzj_files> xzj_files { get; set; }
    }
}
