//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<base_articles> base_articles { get; set; }
        public DbSet<base_menus> base_menus { get; set; }
        public DbSet<base_permissionmenus> base_permissionmenus { get; set; }
        public DbSet<base_permissions> base_permissions { get; set; }
        public DbSet<base_rolepermissions> base_rolepermissions { get; set; }
        public DbSet<base_roles> base_roles { get; set; }
        public DbSet<base_systemlogs> base_systemlogs { get; set; }
        public DbSet<base_units> base_units { get; set; }
        public DbSet<base_unittypes> base_unittypes { get; set; }
        public DbSet<base_userroles> base_userroles { get; set; }
        public DbSet<base_users> base_users { get; set; }
        public DbSet<base_usertypes> base_usertypes { get; set; }
        public DbSet<base_zds> base_zds { get; set; }
        public DbSet<bj_classes> bj_classes { get; set; }
        public DbSet<bj_part> bj_part { get; set; }
        public DbSet<bj_zds> bj_zds { get; set; }
        public DbSet<case_cases> case_cases { get; set; }
        public DbSet<case_casesources> case_casesources { get; set; }
        public DbSet<case_leadersupervises> case_leadersupervises { get; set; }
        public DbSet<case_phases> case_phases { get; set; }
        public DbSet<case_prescriptions> case_prescriptions { get; set; }
        public DbSet<case_simplecases> case_simplecases { get; set; }
        public DbSet<case_sources> case_sources { get; set; }
        public DbSet<case_workflowdetails> case_workflowdetails { get; set; }
        public DbSet<case_workflowspecificactivitys> case_workflowspecificactivitys { get; set; }
        public DbSet<case_workflowspecifics> case_workflowspecifics { get; set; }
        public DbSet<case_workflowspecificusers> case_workflowspecificusers { get; set; }
        public DbSet<case_wtajs> case_wtajs { get; set; }
        public DbSet<case_wtfiles> case_wtfiles { get; set; }
        public DbSet<case_yjdws> case_yjdws { get; set; }
        public DbSet<case_zds> case_zds { get; set; }
        public DbSet<doc_definitions> doc_definitions { get; set; }
        public DbSet<doc_wfdddrs> doc_wfdddrs { get; set; }
        public DbSet<doc_wfsas> doc_wfsas { get; set; }
        public DbSet<fi_camera_units> fi_camera_units { get; set; }
        public DbSet<fi_cameras> fi_cameras { get; set; }
        public DbSet<fi_cameratypes> fi_cameratypes { get; set; }
        public DbSet<fi_specialcameras> fi_specialcameras { get; set; }
        public DbSet<fi_specialunits> fi_specialunits { get; set; }
        public DbSet<fi_uvafiles> fi_uvafiles { get; set; }
        public DbSet<fi_uvas> fi_uvas { get; set; }
        public DbSet<kh_examines> kh_examines { get; set; }
        public DbSet<kh_scores> kh_scores { get; set; }
        public DbSet<low_newlying> low_newlying { get; set; }
        public DbSet<low_oldlying> low_oldlying { get; set; }
        public DbSet<map_customs> map_customs { get; set; }
        public DbSet<mapelementcategory> mapelementcategories { get; set; }
        public DbSet<phone_version> phone_version { get; set; }
        public DbSet<qw_alarmcarmemorylocationdatas> qw_alarmcarmemorylocationdatas { get; set; }
        public DbSet<qw_alarmmemorylocationdatas> qw_alarmmemorylocationdatas { get; set; }
        public DbSet<qw_carhistorypositions> qw_carhistorypositions { get; set; }
        public DbSet<qw_carlastpositions> qw_carlastpositions { get; set; }
        public DbSet<qw_cars> qw_cars { get; set; }
        public DbSet<qw_cartasks> qw_cartasks { get; set; }
        public DbSet<qw_patrolareas> qw_patrolareas { get; set; }
        public DbSet<qw_patrollogs> qw_patrollogs { get; set; }
        public DbSet<qw_signinareas> qw_signinareas { get; set; }
        public DbSet<qw_userhistorypositions> qw_userhistorypositions { get; set; }
        public DbSet<qw_userlastpositions> qw_userlastpositions { get; set; }
        public DbSet<qw_usersignins> qw_usersignins { get; set; }
        public DbSet<qw_usertasks> qw_usertasks { get; set; }
        public DbSet<qw_zds> qw_zds { get; set; }
        public DbSet<report_bureaucenterworks> report_bureaucenterworks { get; set; }
        public DbSet<report_h7n7s> report_h7n7s { get; set; }
        public DbSet<report_infos> report_infos { get; set; }
        public DbSet<report_landlaws> report_landlaws { get; set; }
        public DbSet<report_lawinwaters> report_lawinwaters { get; set; }
        public DbSet<report_safetifyinproductions> report_safetifyinproductions { get; set; }
        public DbSet<report_scalefarmscontrols> report_scalefarmscontrols { get; set; }
        public DbSet<report_specialperiodenvirprots> report_specialperiodenvirprots { get; set; }
        public DbSet<report_strawandwastecontrols> report_strawandwastecontrols { get; set; }
        public DbSet<sm_citizenservices> sm_citizenservices { get; set; }
        public DbSet<sm_classes> sm_classes { get; set; }
        public DbSet<sm_consultations> sm_consultations { get; set; }
        public DbSet<sm_sources> sm_sources { get; set; }
        public DbSet<sm_specialrectifications> sm_specialrectifications { get; set; }
        public DbSet<sm_visits> sm_visits { get; set; }
        public DbSet<systemconfig> systemconfigs { get; set; }
        public DbSet<temp_ajysh> temp_ajysh { get; set; }
        public DbSet<temp_cgd> temp_cgd { get; set; }
        public DbSet<temp_cgs> temp_cgs { get; set; }
        public DbSet<temp_cssbbl> temp_cssbbl { get; set; }
        public DbSet<temp_cyqztzs> temp_cyqztzs { get; set; }
        public DbSet<temp_cyqzwpcltzs> temp_cyqzwpcltzs { get; set; }
        public DbSet<temp_dcqzlxh> temp_dcqzlxh { get; set; }
        public DbSet<temp_dcxwbl> temp_dcxwbl { get; set; }
        public DbSet<temp_ffcwyjs> temp_ffcwyjs { get; set; }
        public DbSet<temp_files> temp_files { get; set; }
        public DbSet<temp_fkcjtzs> temp_fkcjtzs { get; set; }
        public DbSet<temp_fksjpz> temp_fksjpz { get; set; }
        public DbSet<temp_goods> temp_goods { get; set; }
        public DbSet<temp_hgs> temp_hgs { get; set; }
        public DbSet<temp_tzbg> temp_tzbg { get; set; }
        public DbSet<temp_tzbl> temp_tzbl { get; set; }
        public DbSet<temp_tztzs> temp_tztzs { get; set; }
        public DbSet<temp_xcjckybl> temp_xcjckybl { get; set; }
        public DbSet<temp_xwdctzs> temp_xwdctzs { get; set; }
        public DbSet<temp_xzcfjds> temp_xzcfjds { get; set; }
        public DbSet<temp_xzcfjttljl> temp_xzcfjttljl { get; set; }
        public DbSet<temp_xzcfsxgzs> temp_xzcfsxgzs { get; set; }
        public DbSet<temp_ysajsawpqd> temp_ysajsawpqd { get; set; }
        public DbSet<temp_zfwssdhz> temp_zfwssdhz { get; set; }
        public DbSet<temp_zltzwfxwtzs> temp_zltzwfxwtzs { get; set; }
        public DbSet<temp_zlxqgztzs> temp_zlxqgztzs { get; set; }
        public DbSet<temp_zlxqzgzls> temp_zlxqzgzls { get; set; }
        public DbSet<temp_zpzj> temp_zpzj { get; set; }
        public DbSet<tj_persononlines> tj_persononlines { get; set; }
        public DbSet<tj_unitreportcounts> tj_unitreportcounts { get; set; }
        public DbSet<tz_files> tz_files { get; set; }
        public DbSet<tz_registers> tz_registers { get; set; }
        public DbSet<tz_taskclasses> tz_taskclasses { get; set; }
        public DbSet<tz_tztasks> tz_tztasks { get; set; }
        public DbSet<wf_workflowdetails> wf_workflowdetails { get; set; }
        public DbSet<wf_workflows> wf_workflows { get; set; }
        public DbSet<wf_workflowspecificactivitys> wf_workflowspecificactivitys { get; set; }
        public DbSet<wf_workflowspecifics> wf_workflowspecifics { get; set; }
        public DbSet<wf_workflowspecificuserfiles> wf_workflowspecificuserfiles { get; set; }
        public DbSet<wf_workflowspecificusers> wf_workflowspecificusers { get; set; }
        public DbSet<wg_type> wg_type { get; set; }
        public DbSet<wg_unitgrid> wg_unitgrid { get; set; }
        public DbSet<wj_cqxms> wj_cqxms { get; set; }
        public DbSet<wj_files> wj_files { get; set; }
        public DbSet<wj_wzjzs> wj_wzjzs { get; set; }
        public DbSet<xz_licensings> xz_licensings { get; set; }
        public DbSet<xz_threebags> xz_threebags { get; set; }
        public DbSet<xzj_files> xzj_files { get; set; }
        public DbSet<xzsp_disposes> xzsp_disposes { get; set; }
        public DbSet<xzsp_files> xzsp_files { get; set; }
        public DbSet<xzsp_locate> xzsp_locate { get; set; }
        public DbSet<yh_companys> yh_companys { get; set; }
        public DbSet<yh_contracts> yh_contracts { get; set; }
        public DbSet<yh_files> yh_files { get; set; }
        public DbSet<yh_yhlogs> yh_yhlogs { get; set; }
        public DbSet<yh_yhtasks> yh_yhtasks { get; set; }
        public DbSet<zfdx_devices> zfdx_devices { get; set; }
        public DbSet<zfdx_instocks> zfdx_instocks { get; set; }
        public DbSet<zfdx_outstocks> zfdx_outstocks { get; set; }
        public DbSet<zfdx_shopblacks> zfdx_shopblacks { get; set; }
        public DbSet<zfdx_stocks> zfdx_stocks { get; set; }
        public DbSet<zfdx_streetshops> zfdx_streetshops { get; set; }
        public DbSet<zxzz_files> zxzz_files { get; set; }
        public DbSet<zxzz_tasks> zxzz_tasks { get; set; }
        public DbSet<view_casestatistical> view_casestatistical { get; set; }
    }
}
