//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class kh_examines
    {
        public kh_examines()
        {
            this.kh_scores = new HashSet<kh_scores>();
        }
    
        public int examineid { get; set; }
        public Nullable<int> companyid { get; set; }
        public Nullable<int> contractid { get; set; }
        public Nullable<System.DateTime> examinedate { get; set; }
        public Nullable<double> score { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual ICollection<kh_scores> kh_scores { get; set; }
    }
}
