//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class low_newlying
    {
        public int id { get; set; }
        public int lowid { get; set; }
        public string bjz { get; set; }
        public string bjljz { get; set; }
        public Nullable<int> sfbj { get; set; }
        public Nullable<System.DateTime> cjsj { get; set; }
        public string clqk { get; set; }
    }
}
