//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class low_oldlying
    {
        public int id { get; set; }
        public string jkdmc { get; set; }
        public string zt { get; set; }
        public string whdw { get; set; }
        public string whry { get; set; }
        public string bjljz { get; set; }
        public string dz { get; set; }
    }
}
