//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class qw_carlastpositions
    {
        public int carid { get; set; }
        public Nullable<decimal> x84 { get; set; }
        public Nullable<decimal> y84 { get; set; }
        public Nullable<decimal> x2000 { get; set; }
        public Nullable<decimal> y2000 { get; set; }
        public System.DateTime positiontime { get; set; }
        public string cartel { get; set; }
        public Nullable<decimal> speed { get; set; }
        public Nullable<double> lc { get; set; }
        public Nullable<double> yl { get; set; }
        public Nullable<int> pk { get; set; }
    }
}
