//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class qw_cars
    {
        public int carid { get; set; }
        public string code { get; set; }
        public string cartypeid { get; set; }
        public int unitid { get; set; }
        public string carnumber { get; set; }
        public string cartel { get; set; }
        public int isonline { get; set; }
        public int createuserid { get; set; }
        public System.DateTime createtime { get; set; }
        public int status { get; set; }
        public Nullable<int> ssbc { get; set; }
        public Nullable<int> carstatus { get; set; }
        public string remarks { get; set; }
    }
}
