//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class qw_patrollogs
    {
        public int logid { get; set; }
        public Nullable<int> userid { get; set; }
        public string checkid { get; set; }
        public string checkname { get; set; }
        public Nullable<int> isfound { get; set; }
        public Nullable<System.DateTime> reporttime { get; set; }
        public string remark { get; set; }
    }
}
