//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class qw_userlastpositions
    {
        public int userid { get; set; }
        public Nullable<decimal> x84 { get; set; }
        public Nullable<decimal> y84 { get; set; }
        public Nullable<decimal> x2000 { get; set; }
        public Nullable<decimal> y2000 { get; set; }
        public Nullable<System.DateTime> positiontime { get; set; }
        public string imeicode { get; set; }
        public string addresses { get; set; }
        public Nullable<int> ishelp { get; set; }
        public Nullable<System.DateTime> helptime { get; set; }
        public string remarks1 { get; set; }
        public string remarks2 { get; set; }
        public string remarks3 { get; set; }
    }
}
