//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class qw_usersignins
    {
        public int usersigninid { get; set; }
        public int sszd { get; set; }
        public Nullable<int> ssbc { get; set; }
        public int userid { get; set; }
        public System.DateTime signintime { get; set; }
        public double X84 { get; set; }
        public double Y84 { get; set; }
        public double X2000 { get; set; }
        public double Y2000 { get; set; }
        public string remark { get; set; }
    }
}
