//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_scalefarmscontrols
    {
        public int reportid { get; set; }
        public System.DateTime reportdate { get; set; }
        public string unitname { get; set; }
        public int unitid { get; set; }
        public string classname { get; set; }
        public Nullable<int> szcyl { get; set; }
        public Nullable<int> szzfjccs { get; set; }
        public Nullable<int> szzfjcjl { get; set; }
        public Nullable<int> szxqzgtzs { get; set; }
        public Nullable<int> szzgyzwt { get; set; }
        public Nullable<int> szla { get; set; }
        public Nullable<int> szja { get; set; }
        public Nullable<double> szsjjffmk { get; set; }
        public Nullable<int> szyjsfjg { get; set; }
        public Nullable<int> qtj { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> qtry { get; set; }
        public Nullable<int> qtqt { get; set; }
        public Nullable<int> qtzfjccs { get; set; }
        public Nullable<int> qtzfjcjl { get; set; }
        public Nullable<int> qtkjxqzgtzs { get; set; }
        public Nullable<int> qtla { get; set; }
        public Nullable<double> qtsjsjfmk { get; set; }
        public Nullable<int> tqts { get; set; }
        public Nullable<int> tqgb { get; set; }
        public Nullable<int> qtcc { get; set; }
        public Nullable<double> qtccwjmj { get; set; }
        public string zygzld { get; set; }
        public string czdzywt { get; set; }
        public string mldzykn { get; set; }
        public string xgdyjjy { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public Nullable<int> isreport { get; set; }
        public string remark { get; set; }
        public Nullable<int> isstatistics { get; set; }
    }
}
