//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_specialperiodenvirprots
    {
        public Nullable<int> reportid { get; set; }
        public System.DateTime reportdate { get; set; }
        public string unitname { get; set; }
        public int unitid { get; set; }
        public Nullable<int> dccs { get; set; }
        public Nullable<int> cdrs { get; set; }
        public Nullable<int> cdcc { get; set; }
        public Nullable<int> fxs { get; set; }
        public Nullable<int> zgwcs { get; set; }
        public Nullable<int> xzzf { get; set; }
        public Nullable<double> fkje { get; set; }
        public Nullable<int> ffxcgzs { get; set; }
        public Nullable<double> ghzmj { get; set; }
        public Nullable<double> zgzmj { get; set; }
        public Nullable<double> wzqyjzlj { get; set; }
        public Nullable<double> wagdsjqyjzlj { get; set; }
        public Nullable<double> syqdjzlj { get; set; }
        public Nullable<double> gdzbcsctfy { get; set; }
        public Nullable<double> fkjey { get; set; }
        public Nullable<int> zg { get; set; }
        public Nullable<int> qd { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public string statisticsuser { get; set; }
        public string shuser { get; set; }
        public string bzcslshdcqk { get; set; }
        public string fxwtycljg { get; set; }
        public string drjxyrdgzap { get; set; }
        public string xysjcmxtjjsx { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string remark { get; set; }
        public Nullable<int> isreport { get; set; }
        public Nullable<int> isstatistics { get; set; }
    }
}
