//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_strawandwastecontrols
    {
        public int reportid { get; set; }
        public System.DateTime reportdate { get; set; }
        public string unitname { get; set; }
        public int unitid { get; set; }
        public string classname { get; set; }
        public Nullable<int> cdzfry { get; set; }
        public Nullable<int> cdzfcl { get; set; }
        public Nullable<int> kzzfxccs1 { get; set; }
        public Nullable<int> kzzfdccs { get; set; }
        public Nullable<int> kzzfxccs2 { get; set; }
        public Nullable<int> fxczmhd { get; set; }
        public Nullable<double> ghmj1 { get; set; }
        public Nullable<int> fxysjtd { get; set; }
        public Nullable<double> ghmj2 { get; set; }
        public Nullable<int> fxczs { get; set; }
        public Nullable<int> ltfsjgla { get; set; }
        public Nullable<int> ltfsjgja { get; set; }
        public Nullable<double> ltfsjgsjsjfk { get; set; }
        public Nullable<int> nyjyla { get; set; }
        public Nullable<int> nyjyja { get; set; }
        public Nullable<double> nyjysjsjfmk { get; set; }
        public Nullable<int> fscsljla { get; set; }
        public Nullable<int> fscsljja { get; set; }
        public Nullable<double> fscsljsjsjfmk { get; set; }
        public string zygzld { get; set; }
        public string czdzywt { get; set; }
        public string mldzykn { get; set; }
        public string xgdyjjy { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string remark { get; set; }
        public Nullable<int> isreport { get; set; }
        public Nullable<int> isstatistics { get; set; }
    }
}
