//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_bureaucenterworks
    {
        public int reportid { get; set; }
        public System.DateTime reportdate { get; set; }
        public string unitname { get; set; }
        public int unitid { get; set; }
        public string classname { get; set; }
        public Nullable<double> czczmj { get; set; }
        public Nullable<double> czccmj { get; set; }
        public Nullable<int> czla { get; set; }
        public Nullable<int> czja { get; set; }
        public Nullable<double> czsjsjfmk { get; set; }
        public Nullable<double> czxzccmj { get; set; }
        public Nullable<double> czzsmj { get; set; }
        public Nullable<int> kzzfcs { get; set; }
        public Nullable<int> zlxqzgtzs { get; set; }
        public Nullable<double> qlczmj { get; set; }
        public Nullable<double> qlczsl { get; set; }
        public string fzhdmc { get; set; }
        public string xccs { get; set; }
        public string fxzghdwt { get; set; }
        public string gmczf { get; set; }
        public string shzf { get; set; }
        public string jgcsljfs { get; set; }
        public Nullable<int> cccztsjb { get; set; }
        public Nullable<int> ccyyla { get; set; }
        public Nullable<double> ccsjsjfmk { get; set; }
        public Nullable<double> dlczzwt { get; set; }
        public Nullable<int> dlcztsjb { get; set; }
        public Nullable<int> dlla { get; set; }
        public Nullable<double> dlsjsjfmk { get; set; }
        public Nullable<int> ccyyczzwt { get; set; }
        public string zygzld { get; set; }
        public string czdzywt { get; set; }
        public string mldzykn { get; set; }
        public string xgdyjjy { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string remark { get; set; }
        public Nullable<int> isreport { get; set; }
        public Nullable<int> isstatistics { get; set; }
    }
}
