//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_h7n7s
    {
        public Nullable<int> reportid { get; set; }
        public Nullable<int> cdcl { get; set; }
        public Nullable<int> ffxczl { get; set; }
        public Nullable<int> qlhqjy { get; set; }
        public Nullable<int> cchqjy { get; set; }
        public Nullable<int> czhqsl { get; set; }
        public string qt { get; set; }
        public string drgzzf { get; set; }
        public System.DateTime reportdate { get; set; }
        public string unitname { get; set; }
        public int unitid { get; set; }
        public Nullable<int> xccs { get; set; }
        public Nullable<int> cdry { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string remark { get; set; }
        public Nullable<int> isreport { get; set; }
        public Nullable<int> isstatistics { get; set; }
    }
}
