//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_infos
    {
        public int reportid { get; set; }
        public string reportname { get; set; }
        public Nullable<int> reporttype { get; set; }
        public string statistics { get; set; }
        public Nullable<int> isenable { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<System.DateTime> whattime { get; set; }
    }
}
