//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_landlaws
    {
        public int reportid { get; set; }
        public System.DateTime reportdate { get; set; }
        public string unitname { get; set; }
        public int unitid { get; set; }
        public string classname { get; set; }
        public Nullable<double> wfydajzjs { get; set; }
        public Nullable<double> gtbmyss { get; set; }
        public Nullable<double> zhzfbmslyss { get; set; }
        public Nullable<double> xdcfjdsjs { get; set; }
        public Nullable<double> sqqzzxjs { get; set; }
        public Nullable<double> lacczjs { get; set; }
        public Nullable<double> sazmj { get; set; }
        public Nullable<double> qzgdmj { get; set; }
        public Nullable<double> fkje { get; set; }
        public Nullable<double> msmj { get; set; }
        public Nullable<double> ccwfjzmj { get; set; }
        public Nullable<double> mswfsd { get; set; }
        public Nullable<double> tccfjy { get; set; }
        public Nullable<double> sjcf { get; set; }
        public Nullable<double> cfqt { get; set; }
        public Nullable<double> ysgajg { get; set; }
        public Nullable<double> cqqzcs { get; set; }
        public Nullable<double> zjxszr { get; set; }
        public Nullable<double> zjxszrqt { get; set; }
        public Nullable<double> yjajs { get; set; }
        public Nullable<double> wjazjs { get; set; }
        public Nullable<double> nysd { get; set; }
        public Nullable<double> yysd { get; set; }
        public string zygzld { get; set; }
        public string czdzywt { get; set; }
        public string mldzykn { get; set; }
        public string xgdyjjy { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string remark { get; set; }
        public Nullable<int> isreport { get; set; }
        public Nullable<int> isstatistics { get; set; }
    }
}
