//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_lawinwaters
    {
        public int reportid { get; set; }
        public System.DateTime reportdate { get; set; }
        public string unitname { get; set; }
        public int unitid { get; set; }
        public string classname { get; set; }
        public Nullable<int> cdzfry { get; set; }
        public Nullable<int> cdzfcl { get; set; }
        public Nullable<int> kzzfxccs { get; set; }
        public Nullable<int> zlxqzgtzs { get; set; }
        public Nullable<int> fxsswt { get; set; }
        public Nullable<int> wczgsswt { get; set; }
        public Nullable<int> jsys { get; set; }
        public Nullable<int> jcfx { get; set; }
        public Nullable<int> tsjb { get; set; }
        public Nullable<int> zlas { get; set; }
        public Nullable<int> jsfaxhdjzw { get; set; }
        public Nullable<int> hdfqw { get; set; }
        public Nullable<int> pslj { get; set; }
        public Nullable<int> ncgsl { get; set; }
        public Nullable<int> csgsl { get; set; }
        public Nullable<int> psywscll { get; set; }
        public Nullable<int> jas { get; set; }
        public Nullable<double> sjsjfmk { get; set; }
        public string zygzld { get; set; }
        public string czdzywt { get; set; }
        public string mldzykn { get; set; }
        public string xgdyjjy { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string remark { get; set; }
        public Nullable<int> isreport { get; set; }
        public Nullable<int> isstatistics { get; set; }
        public string preparer { get; set; }
        public string preparerphone { get; set; }
        public string shuser { get; set; }
    }
}
