//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_safetifyinproductions
    {
        public int reportid { get; set; }
        public System.DateTime reportdate { get; set; }
        public string unitname { get; set; }
        public int unitid { get; set; }
        public string classname { get; set; }
        public Nullable<int> cdzfry { get; set; }
        public Nullable<int> jcscjydw { get; set; }
        public Nullable<int> fxaqyh { get; set; }
        public Nullable<int> wczgaqyh { get; set; }
        public Nullable<int> xcjcjl { get; set; }
        public Nullable<int> zlxqzgzls { get; set; }
        public Nullable<int> xcclcsjds { get; set; }
        public Nullable<int> zgfcyjs { get; set; }
        public Nullable<int> jsys { get; set; }
        public Nullable<int> jcfx { get; set; }
        public Nullable<int> xswy { get; set; }
        public Nullable<int> la { get; set; }
        public Nullable<int> ja { get; set; }
        public Nullable<int> jg { get; set; }
        public Nullable<double> sjsjfmk { get; set; }
        public Nullable<int> tctyzd { get; set; }
        public Nullable<int> tqgb { get; set; }
        public string zygzld { get; set; }
        public string czdzywt { get; set; }
        public string mldzykn { get; set; }
        public string xgdyjjy { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string remark { get; set; }
        public Nullable<int> isreport { get; set; }
        public Nullable<int> isstatistics { get; set; }
        public Nullable<int> jdfke { get; set; }
        public Nullable<int> zyfzr { get; set; }
        public Nullable<int> aqsctj { get; set; }
        public Nullable<int> pxhczglgd { get; set; }
        public Nullable<int> sgyhpc { get; set; }
        public Nullable<int> stsgd { get; set; }
        public Nullable<int> sbglhjycsgd { get; set; }
        public Nullable<int> ldbhldhtgl { get; set; }
        public Nullable<int> yxkjzy { get; set; }
        public Nullable<int> dwjjzajdgl { get; set; }
        public string preparer { get; set; }
        public string shuser { get; set; }
        public string preparerphone { get; set; }
    }
}
