//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_citizenservices
    {
        public sm_citizenservices()
        {
            this.sm_visits = new HashSet<sm_visits>();
        }
    
        public string citizenid { get; set; }
        public int sourceid { get; set; }
        public System.DateTime dutytime { get; set; }
        public string eventid { get; set; }
        public string complainant { get; set; }
        public Nullable<int> cnumber { get; set; }
        public System.DateTime foundtime { get; set; }
        public string contactphone { get; set; }
        public string contactaddress { get; set; }
        public string eventaddress { get; set; }
        public string eventtitle { get; set; }
        public string eventcontent { get; set; }
        public int bigtypeid { get; set; }
        public int smalltypeid { get; set; }
        public System.DateTime limittime { get; set; }
        public string recorduser { get; set; }
        public string grometry { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> createuserid { get; set; }
        public int sfzxzz { get; set; }
        public Nullable<int> srid { get; set; }
        public string processmode { get; set; }
        public string satisfaction { get; set; }
        public Nullable<System.DateTime> gdsj { get; set; }
        public Nullable<int> processuserid { get; set; }
        public Nullable<int> officeuserid { get; set; }
        public Nullable<int> isextension { get; set; }
        public Nullable<int> reviewextension { get; set; }
        public Nullable<int> extensiontime { get; set; }
        public string extensioncontent { get; set; }
        public Nullable<int> istz { get; set; }
        public string auditopinion { get; set; }
        public string workflowtype { get; set; }
        public string suggest { get; set; }
        public Nullable<int> xzid { get; set; }
        public string pqxzid { get; set; }
    
        public virtual sm_sources sm_sources { get; set; }
        public virtual ICollection<sm_visits> sm_visits { get; set; }
    }
}
