//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_consultations
    {
        public int consultid { get; set; }
        public string consultuser { get; set; }
        public string contact { get; set; }
        public string title { get; set; }
        public int bigtypeid { get; set; }
        public int smalltypeid { get; set; }
        public Nullable<System.DateTime> acceptancetime { get; set; }
        public string consultcontent { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> createuserid { get; set; }
    }
}
