//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_sources
    {
        public sm_sources()
        {
            this.sm_citizenservices = new HashSet<sm_citizenservices>();
        }
    
        public int sourceid { get; set; }
        public string name { get; set; }
        public string spath { get; set; }
    
        public virtual ICollection<sm_citizenservices> sm_citizenservices { get; set; }
    }
}
