//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_visits
    {
        public int visitid { get; set; }
        public string citizenid { get; set; }
        public Nullable<System.DateTime> visittime { get; set; }
        public string respondents { get; set; }
        public string contact { get; set; }
        public Nullable<int> returnvisit { get; set; }
        public string returnvisitcontent { get; set; }
        public Nullable<int> satisfaction { get; set; }
        public Nullable<int> processmode { get; set; }
        public string processopinion { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> createuserid { get; set; }
    
        public virtual sm_citizenservices sm_citizenservices { get; set; }
    }
}
