//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_tzbl
    {
        public int id { get; set; }
        public string ajmc { get; set; }
        public string ajbh { get; set; }
        public string tzrq { get; set; }
        public string tzkssj { get; set; }
        public string tzjssj { get; set; }
        public string tzdd { get; set; }
        public string tzfs { get; set; }
        public string tzsqr { get; set; }
        public string fzr { get; set; }
        public string xb { get; set; }
        public string gzdw { get; set; }
        public string zwhzy { get; set; }
        public string sfzh { get; set; }
        public string zzhzs { get; set; }
        public string yb { get; set; }
        public string dh { get; set; }
        public string wtdlr1 { get; set; }
        public string xb1 { get; set; }
        public string sfzh1 { get; set; }
        public string gzdw1 { get; set; }
        public string zw1 { get; set; }
        public string dh1 { get; set; }
        public string wtdlr2 { get; set; }
        public string xb2 { get; set; }
        public string sfzh2 { get; set; }
        public string gzdw2 { get; set; }
        public string zw2 { get; set; }
        public string dh2 { get; set; }
        public string qtcjr { get; set; }
        public string ajdcr1 { get; set; }
        public string gzdwjzw1 { get; set; }
        public string ajdcr2 { get; set; }
        public string gzdwjzw2 { get; set; }
        public string tzzcr { get; set; }
        public string tzr { get; set; }
        public string jlr { get; set; }
        public string gzdw3 { get; set; }
        public string tzbl { get; set; }
    }
}
