//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_dcxwbl
    {
        public int id { get; set; }
        public string casereason { get; set; }
        public string dcdate { get; set; }
        public string sdctime { get; set; }
        public string edctime { get; set; }
        public string dcplace { get; set; }
        public string bdcuser { get; set; }
        public string sex { get; set; }
        public string mz { get; set; }
        public string sfz { get; set; }
        public string gzdw { get; set; }
        public string zwzy { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string zipcode { get; set; }
        public string ybagx { get; set; }
        public string zdcxwr { get; set; }
        public string zzfzh { get; set; }
        public string xdcxwr { get; set; }
        public string xzfzh { get; set; }
        public string jlperson { get; set; }
        public string zcperson { get; set; }
        public string sfqr { get; set; }
        public string sfhb { get; set; }
        public string sftq { get; set; }
        public string remark { get; set; }
    }
}
