//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_ffcwyjs
    {
        public int id { get; set; }
        public string yjdw { get; set; }
        public string dsr { get; set; }
        public string wfsj { get; set; }
        public string wfdd { get; set; }
        public string rdwfssms { get; set; }
        public string wfdfl { get; set; }
        public string jdskjrq { get; set; }
        public string jdsbh { get; set; }
    }
}
