//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_xzcfjds
    {
        public int id { get; set; }
        public string wsbh { get; set; }
        public string dsr { get; set; }
        public string xb { get; set; }
        public string dwmc { get; set; }
        public string fddbr { get; set; }
        public string zjlx { get; set; }
        public string zjh { get; set; }
        public string address { get; set; }
        public string jdszw { get; set; }
    }
}
