//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_cyqzwpcltzs
    {
        public int id { get; set; }
        public string wsbh { get; set; }
        public string dsr { get; set; }
        public string qztzsj { get; set; }
        public string qzwp { get; set; }
        public string yjdflgd { get; set; }
        public string cyqztzsbh { get; set; }
        public string cljg { get; set; }
        public string bcyqzr { get; set; }
        public string tzsj { get; set; }
        public string zfry { get; set; }
        public string zfsj { get; set; }
    }
}
