//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_ysajsawpqd
    {
        public int id { get; set; }
        public string ysdw { get; set; }
        public string ysajjsr { get; set; }
        public string jssj { get; set; }
        public string ysajysr { get; set; }
        public string yssj { get; set; }
    }
}
