//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_goods
    {
        public int id { get; set; }
        public Nullable<int> documentid { get; set; }
        public string documentname { get; set; }
        public string goodsname { get; set; }
        public string goodscount { get; set; }
        public string goodspj { get; set; }
        public string goodsgg { get; set; }
        public string goodsxh { get; set; }
        public string goodsxt { get; set; }
        public string goodsremark { get; set; }
    }
}
