//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_cssbbl
    {
        public int id { get; set; }
        public string sbsj { get; set; }
        public string sbdd { get; set; }
        public string dsrjbqk { get; set; }
        public string sx { get; set; }
        public string cssbnr { get; set; }
    }
}
