//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_xwdctzs
    {
        public int id { get; set; }
        public string wsbh { get; set; }
        public string dsr { get; set; }
        public string afsj { get; set; }
        public string afdd { get; set; }
        public string dcxwsj { get; set; }
        public string dcxwdd { get; set; }
        public string wfgd { get; set; }
        public string clsfz { get; set; }
        public string clyyzz { get; set; }
        public string clsfzmhwts { get; set; }
        public string clqtzm { get; set; }
        public string lxr { get; set; }
        public string lxdh { get; set; }
        public string lxdz { get; set; }
        public string fcrq { get; set; }
    }
}
