//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_zlxqgztzs
    {
        public int id { get; set; }
        public string wsbh { get; set; }
        public string dsr { get; set; }
        public string afsj { get; set; }
        public string afdz { get; set; }
        public string wfxw { get; set; }
        public string flyj { get; set; }
        public string gznr { get; set; }
        public string zlgzqx { get; set; }
        public string tzsj { get; set; }
        public string zfry1 { get; set; }
        public string zfzh1 { get; set; }
        public string zfry2 { get; set; }
        public string zfzh2 { get; set; }
        public string lxdh { get; set; }
        public string lxdz { get; set; }
    }
}
