//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_xcjckybl
    {
        public int id { get; set; }
        public string jcdate { get; set; }
        public string sjctime { get; set; }
        public string ejctime { get; set; }
        public string jcplace { get; set; }
        public string zkyr { get; set; }
        public string zdwzw { get; set; }
        public string xkyr { get; set; }
        public string xdwzw { get; set; }
        public string dsr { get; set; }
        public string dsrdwzw { get; set; }
        public string xcfzr { get; set; }
        public string xcdwzw { get; set; }
        public string byqr { get; set; }
        public string byqdwzw { get; set; }
        public string jlr { get; set; }
        public string jlrdwzw { get; set; }
        public string zzfry { get; set; }
        public string xzfry { get; set; }
        public string zzjhm { get; set; }
        public string xzjhm { get; set; }
        public string xcqk { get; set; }
        public string jzr { get; set; }
    }
}
