//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_tzbg
    {
        public int id { get; set; }
        public string ajmc { get; set; }
        public string ajbh { get; set; }
        public string tzrq { get; set; }
        public string tzstime { get; set; }
        public string tzetime { get; set; }
        public string tzdd { get; set; }
        public string tzfs { get; set; }
        public string tzzcr1 { get; set; }
        public string tzy1 { get; set; }
        public string jlr { get; set; }
        public string tzsqr { get; set; }
        public string fddbr { get; set; }
        public string wtdlr { get; set; }
        public string ajdcr { get; set; }
        public string gzdw { get; set; }
        public string tzhjbqk { get; set; }
        public string ajss { get; set; }
        public string clyjjjy { get; set; }
        public string tzzcr2 { get; set; }
        public string tzy2 { get; set; }
    }
}
