//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_xzcfjttljl
    {
        public int id { get; set; }
        public string ajmc { get; set; }
        public string kssj { get; set; }
        public string jssj { get; set; }
        public string dd { get; set; }
        public string zcr { get; set; }
        public string hbr { get; set; }
        public string jlr { get; set; }
        public string cxryxmjzw { get; set; }
        public string tlnr { get; set; }
        public string tljl { get; set; }
        public string zjxyj { get; set; }
    }
}
