//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tz_registers
    {
        public int registerid { get; set; }
        public string title { get; set; }
        public System.DateTime registertime { get; set; }
        public string people { get; set; }
        public string address { get; set; }
        public string taskclassid { get; set; }
        public string content { get; set; }
        public string remark { get; set; }
        public int createuserid { get; set; }
        public System.DateTime createtime { get; set; }
        public string eventid { get; set; }
        public int unitid { get; set; }
        public string wordname { get; set; }
        public string wordpath { get; set; }
    }
}
