//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tz_taskclasses
    {
        public int taskclassid { get; set; }
        public Nullable<int> taskid { get; set; }
        public string classid { get; set; }
        public Nullable<int> sszd { get; set; }
        public Nullable<System.DateTime> tasktime { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual tz_tztasks tz_tztasks { get; set; }
    }
}
