//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_casestatistical
    {
        public string wfsaid { get; set; }
        public string wfsid { get; set; }
        public string wfsid2 { get; set; }
        public string wfsname { get; set; }
        public string currentwfsaid { get; set; }
        public Nullable<int> filestatus { get; set; }
        public Nullable<int> casetype { get; set; }
        public Nullable<int> casesourceid { get; set; }
        public string casename { get; set; }
        public string casereason { get; set; }
        public string contact { get; set; }
        public string contactphone { get; set; }
        public string address { get; set; }
        public string casebh { get; set; }
        public string casetypeid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string sourcename { get; set; }
        public string wfdid { get; set; }
        public Nullable<System.DateTime> dealtime { get; set; }
        public string zd_name { get; set; }
        public Nullable<double> term { get; set; }
        public Nullable<System.DateTime> etime { get; set; }
        public string dealusername { get; set; }
        public string dealunitname { get; set; }
        public Nullable<int> zbunitid { get; set; }
        public string zbunitname { get; set; }
        public string rezbunitname { get; set; }
        public Nullable<int> caseid { get; set; }
        public string p_name { get; set; }
        public string f_name { get; set; }
        public Nullable<System.DateTime> sitedatetime { get; set; }
        public string caseaddress { get; set; }
        public string zbusername { get; set; }
        public string xbusername { get; set; }
        public Nullable<System.DateTime> ay_createtime { get; set; }
        public string ysh_ysrq { get; set; }
        public Nullable<System.DateTime> dczj_createtime { get; set; }
        public Nullable<System.DateTime> sxgz_createtime { get; set; }
        public Nullable<System.DateTime> cfjd_createtime { get; set; }
        public Nullable<System.DateTime> ajja_createtime { get; set; }
        public Nullable<System.DateTime> cssbtime { get; set; }
        public Nullable<System.DateTime> tzcltime { get; set; }
        public Nullable<System.DateTime> xzcfbgcltime { get; set; }
        public string xzcfnr { get; set; }
        public string xzcfje { get; set; }
        public Nullable<System.DateTime> fkjntime { get; set; }
        public string fkpjbh { get; set; }
        public string cgsj { get; set; }
        public Nullable<System.DateTime> dw_ga { get; set; }
        public Nullable<System.DateTime> dw_gz { get; set; }
        public Nullable<System.DateTime> dw_jw { get; set; }
        public Nullable<System.DateTime> dw_fy { get; set; }
        public string classname { get; set; }
        public string ysh_hhsj { get; set; }
        public string zdmj { get; set; }
        public string gdmj { get; set; }
        public string gtjzmj { get; set; }
        public string ghjzmj { get; set; }
        public string sqsj { get; set; }
        public string zxsj { get; set; }
        public string remark { get; set; }
    }
}
