//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wf_workflows
    {
        public wf_workflows()
        {
            this.wf_workflowdetails = new HashSet<wf_workflowdetails>();
            this.wf_workflowspecifics = new HashSet<wf_workflowspecifics>();
        }
    
        public string wfid { get; set; }
        public string wfname { get; set; }
        public Nullable<int> wftypeid { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> status { get; set; }
        public string tablename { get; set; }
        public string wfpic { get; set; }
    
        public virtual ICollection<wf_workflowdetails> wf_workflowdetails { get; set; }
        public virtual ICollection<wf_workflowspecifics> wf_workflowspecifics { get; set; }
    }
}
