//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wf_workflowspecifics
    {
        public wf_workflowspecifics()
        {
            this.wf_workflowspecificactivitys = new HashSet<wf_workflowspecificactivitys>();
        }
    
        public string wfsid { get; set; }
        public string wfid { get; set; }
        public string tablename { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> status { get; set; }
        public string tablenameid { get; set; }
        public string wfsname { get; set; }
        public string currentwfsaid { get; set; }
        public Nullable<int> filestatus { get; set; }
    
        public virtual wf_workflows wf_workflows { get; set; }
        public virtual ICollection<wf_workflowspecificactivitys> wf_workflowspecificactivitys { get; set; }
    }
}
