//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wf_workflowdetails
    {
        public wf_workflowdetails()
        {
            this.wf_workflowspecificactivitys = new HashSet<wf_workflowspecificactivitys>();
        }
    
        public string wfdid { get; set; }
        public string wfid { get; set; }
        public string wfdname { get; set; }
        public string nextid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> iscurentuserdept { get; set; }
        public Nullable<int> isuser { get; set; }
        public string uservalue { get; set; }
        public Nullable<int> isdept { get; set; }
        public string deptvalue { get; set; }
        public Nullable<int> isrole { get; set; }
        public string rolevalue { get; set; }
        public Nullable<int> seqnum { get; set; }
        public string nextiddefault { get; set; }
        public string nextiddefaultuser { get; set; }
        public string nextiddefaultdept { get; set; }
        public string nextiddefaultrole { get; set; }
    
        public virtual wf_workflows wf_workflows { get; set; }
        public virtual ICollection<wf_workflowspecificactivitys> wf_workflowspecificactivitys { get; set; }
    }
}
