//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wf_workflowspecificactivitys
    {
        public wf_workflowspecificactivitys()
        {
            this.wf_workflowspecificusers = new HashSet<wf_workflowspecificusers>();
        }
    
        public string wfsaid { get; set; }
        public string wfsid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> dealuserid { get; set; }
        public Nullable<System.DateTime> dealtime { get; set; }
        public string wfdid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    
        public virtual wf_workflowdetails wf_workflowdetails { get; set; }
        public virtual wf_workflowspecifics wf_workflowspecifics { get; set; }
        public virtual ICollection<wf_workflowspecificusers> wf_workflowspecificusers { get; set; }
    }
}
