//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wf_workflowspecificuserfiles
    {
        public int fileid { get; set; }
        public string wfsuid { get; set; }
        public Nullable<int> filesource { get; set; }
        public string filepath { get; set; }
        public string filename { get; set; }
        public string fileremark { get; set; }
        public string filetype { get; set; }
        public Nullable<double> filesize { get; set; }
    
        public virtual wf_workflowspecificusers wf_workflowspecificusers { get; set; }
    }
}
