//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wj_cqxms
    {
        public int cqid { get; set; }
        public string projectname { get; set; }
        public string projectleader { get; set; }
        public string contackphone { get; set; }
        public Nullable<double> cqarea { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public string ssqy { get; set; }
        public string address { get; set; }
        public string geography { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> createuserid { get; set; }
    }
}
