//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wj_files
    {
        public int fileid { get; set; }
        public string filetype { get; set; }
        public string filename { get; set; }
        public string filepath { get; set; }
        public Nullable<int> source { get; set; }
        public Nullable<int> sourceid { get; set; }
        public Nullable<double> filesize { get; set; }
    }
}
