//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wj_wzjzs
    {
        public int wjid { get; set; }
        public string wjholder { get; set; }
        public string contactphone { get; set; }
        public string holderidentity { get; set; }
        public Nullable<int> householdnum { get; set; }
        public string address { get; set; }
        public string landproperty { get; set; }
        public Nullable<System.DateTime> completiontime { get; set; }
        public string landnum { get; set; }
        public string propertynum { get; set; }
        public Nullable<double> coverarea { get; set; }
        public Nullable<double> buildarea { get; set; }
        public string builduse { get; set; }
        public string buildstructure { get; set; }
        public Nullable<int> buildlayers_up { get; set; }
        public Nullable<int> buildlayers_down { get; set; }
        public string geography { get; set; }
        public string wj_wjtype { get; set; }
        public string wj_use { get; set; }
        public string wj_land { get; set; }
        public Nullable<System.DateTime> wj_time { get; set; }
        public Nullable<double> wj_landarea { get; set; }
        public string wj_wjarea { get; set; }
        public string wj_buildstructure { get; set; }
        public string wj_layerup { get; set; }
        public string wj_layerdown { get; set; }
        public Nullable<int> process { get; set; }
        public Nullable<int> isgd { get; set; }
        public string reportuser { get; set; }
        public Nullable<System.DateTime> reporttime { get; set; }
        public Nullable<System.DateTime> foundtime { get; set; }
        public string remark { get; set; }
        public Nullable<int> parentid { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string citizenid { get; set; }
        public Nullable<System.DateTime> limittime { get; set; }
    }
}
