//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW_WORKITEM_HISTORY_W
    {
        public string ROWGUID { get; set; }
        public Nullable<System.DateTime> DATA_TIMESTAMP { get; set; }
        public string AGENTFORWORKITEMGUID { get; set; }
        public Nullable<System.DateTime> TERMINATEDATE { get; set; }
        public string OPERATORFORDISPLAYGUID { get; set; }
        public string OPERATORFORDISPLAYNAME { get; set; }
        public string NOTE { get; set; }
        public string SYNC { get; set; }
        public string WORKITEMGUID { get; set; }
        public string ACTIVITYGUID { get; set; }
        public string ACTIVITYNAME { get; set; }
        public string ACTIVITYINSTANCEGUID { get; set; }
        public string WORKITEMNAME { get; set; }
        public string WORKITEMTYPE { get; set; }
        public string WORKITEMMODENAME { get; set; }
        public string HANDLEURL { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public string SENDERGUID { get; set; }
        public string SENDERNAME { get; set; }
        public string TRANSACTOR { get; set; }
        public string TRANSACTORNAME { get; set; }
        public string JOBGUID { get; set; }
        public string OPERATIONGUID { get; set; }
        public Nullable<System.DateTime> READDATE { get; set; }
        public Nullable<System.DateTime> OPERATIONDATE { get; set; }
        public string OPERATORGUID { get; set; }
        public string OPERATORNAME { get; set; }
        public string OPINION { get; set; }
        public string WAITHANDLEGUID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<System.DateTime> TERMINATEDATA { get; set; }
        public Nullable<decimal> STATUSBEFORETERMINATE { get; set; }
        public Nullable<decimal> LIMITMINUTES { get; set; }
        public string PROCESSGUID { get; set; }
        public string PROCESSVERSIONGUID { get; set; }
        public string PROCESSVERSIONNAME { get; set; }
        public string PROCESSVERSIONINSTANCEGUID { get; set; }
        public string PROCESSVERSIONINSTANCENAME { get; set; }
        public string GROUPGUID { get; set; }
        public Nullable<decimal> IS_LOCKED { get; set; }
        public string LOCKERUSERGUID { get; set; }
        public string LOCKERDISPNAME { get; set; }
        public Nullable<System.DateTime> LOCKDATE { get; set; }
        public string AGENTFORUSERGUID { get; set; }
        public string OPERATIONTYPE { get; set; }
        public string LOCKERWINDOWGUID { get; set; }
        public string ABAUDITOPINION { get; set; }
        public Nullable<decimal> TIMELIMIT { get; set; }
        public Nullable<decimal> TIMELIMITUNIT { get; set; }
        public Nullable<System.DateTime> OVERTIMEPOINT { get; set; }
        public Nullable<System.DateTime> EARLYWARNINGPOINT { get; set; }
        public Nullable<decimal> IS_NEEDSENDEARLYWARNING { get; set; }
        public Nullable<decimal> IS_NEEDSENDOVERTIMENOTIFY { get; set; }
        public string SYNCROWGUID { get; set; }
    }
}
