//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xz_licensings
    {
        public int licensingid { get; set; }
        public string xksx { get; set; }
        public string licensingnum { get; set; }
        public int sph { get; set; }
        public string splx { get; set; }
        public string b_address { get; set; }
        public string sxmx { get; set; }
        public string sqr { get; set; }
        public string cardtype { get; set; }
        public string card { get; set; }
        public string contactphone { get; set; }
        public string s_address { get; set; }
        public System.DateTime processtime_start { get; set; }
        public string processcontent { get; set; }
        public string processaddress { get; set; }
        public string geography { get; set; }
        public int createuserid { get; set; }
        public System.DateTime createtime { get; set; }
        public int shresult { get; set; }
        public string shopinion { get; set; }
        public int shuser { get; set; }
        public int issh { get; set; }
        public System.DateTime shtime { get; set; }
        public Nullable<System.DateTime> processtime_end { get; set; }
    }
}
