//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xz_threebags
    {
        public int storeid { get; set; }
        public string storename { get; set; }
        public string storetype { get; set; }
        public string person { get; set; }
        public string card { get; set; }
        public string contactphone { get; set; }
        public string address { get; set; }
        public string geography { get; set; }
        public string remark { get; set; }
        public int createuserid { get; set; }
        public System.DateTime createtime { get; set; }
    }
}
