//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xzsp_disposes
    {
        public int id { get; set; }
        public string xzspid { get; set; }
        public Nullable<int> stage { get; set; }
        public Nullable<int> disposeuserid { get; set; }
        public Nullable<int> disposestate { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> disposetime { get; set; }
        public Nullable<int> parentid { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public string address { get; set; }
    }
}
