//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class yh_contracts
    {
        public int contractid { get; set; }
        public string contractname { get; set; }
        public string patrolexplain { get; set; }
        public string contractnum { get; set; }
        public string jfdw { get; set; }
        public string jfdb { get; set; }
        public string yfdw { get; set; }
        public string yfdb { get; set; }
        public string jldw { get; set; }
        public System.DateTime starttime { get; set; }
        public System.DateTime endtime { get; set; }
        public System.DateTime signdate { get; set; }
        public double summoney { get; set; }
        public int htzxzt { get; set; }
        public double currentmoney { get; set; }
        public System.DateTime contactendtime { get; set; }
        public string contacttype { get; set; }
        public string contracttype { get; set; }
        public int createuserid { get; set; }
        public System.DateTime createtime { get; set; }
        public Nullable<double> patrolemoney { get; set; }
        public Nullable<double> yhmoney { get; set; }
    }
}
