//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class yh_companys
    {
        public int companyid { get; set; }
        public string companyname { get; set; }
        public string legal { get; set; }
        public string contact { get; set; }
        public string mobilephone { get; set; }
        public string telephone { get; set; }
        public string faxnumber { get; set; }
        public string email { get; set; }
        public string companytype { get; set; }
        public string address { get; set; }
        public Nullable<int> isenadle { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
