//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class yh_yhlogs
    {
        public int yhlogid { get; set; }
        public int yhcontract { get; set; }
        public System.DateTime patroltime { get; set; }
        public string patrolexplain { get; set; }
        public System.DateTime createtime { get; set; }
        public int createuserid { get; set; }
    }
}
