//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class yh_yhtasks
    {
        public string yhtaskid { get; set; }
        public int yhcompany { get; set; }
        public System.DateTime foundtime { get; set; }
        public string fileename { get; set; }
        public string wtsource { get; set; }
        public string yhtype { get; set; }
        public string wtbigclass { get; set; }
        public string wtsmallclass { get; set; }
        public string yhobject { get; set; }
        public string weather { get; set; }
        public Nullable<double> duetime { get; set; }
        public Nullable<double> outlay { get; set; }
        public Nullable<double> workload { get; set; }
        public int yhcontract { get; set; }
        public string wtaddress { get; set; }
        public string wtdescribe { get; set; }
        public string geography84 { get; set; }
        public string geography2000 { get; set; }
        public string wtnature { get; set; }
        public Nullable<double> points { get; set; }
        public Nullable<double> debit { get; set; }
        public string sendusername { get; set; }
        public string sendopinion { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<int> pqrid { get; set; }
    }
}
