//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class zfdx_streetshops
    {
        public int zfdx_shopid { get; set; }
        public string shopname { get; set; }
        public string shoptype { get; set; }
        public string person { get; set; }
        public string card { get; set; }
        public string contactphone { get; set; }
        public Nullable<int> staffsum { get; set; }
        public Nullable<System.DateTime> e_licence { get; set; }
        public Nullable<System.DateTime> s_licence { get; set; }
        public string licencecard { get; set; }
        public Nullable<System.DateTime> s_business { get; set; }
        public Nullable<System.DateTime> e_business { get; set; }
        public Nullable<double> businessarea { get; set; }
        public string address { get; set; }
        public string sourcearea { get; set; }
        public string grometry { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> sstype { get; set; }
        public string hawkertype { get; set; }
        public string remark { get; set; }
    }
}
