//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class zxzz_tasks
    {
        public string taskid { get; set; }
        public string title { get; set; }
        public string tasktype { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<int> term { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public string region { get; set; }
        public string taskexplain { get; set; }
        public string grometry { get; set; }
        public Nullable<int> fqr { get; set; }
        public Nullable<System.DateTime> fqtime { get; set; }
        public string xdzd { get; set; }
        public string leader { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> summarytime { get; set; }
        public Nullable<int> summaryuserid { get; set; }
        public string summary { get; set; }
        public string results { get; set; }
        public string experiences { get; set; }
    }
}
