Ext.define('TianZun.model.reportcenter.lawInWaterModel', {
    extend: 'Ext.data.Model',
    idProperty: 'taskId',
    fields: [
               { name: 'projectId', type: 'float' },
               { name: 'project', type: 'string' },
               { name: 'taskId', type: 'float' },
               { name: 'classname', type: 'string' },
               { name: 'unitname', type: 'string' },
               { name: 'cdzfry', type: 'int', convert: function (value) { return value == null ? 0 : value } },
               { name: 'cdzfcl', type: 'int', convert: function (value) { return value == null ? 0 : value } },
               { name: 'kzzfxccs',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'zlxqzgtzs',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'fxsswt',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'wczgsswt',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'jsys',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'jcfx',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'tsjb',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'zlas',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'jsfaxhdjzw',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'hdfqw',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'pslj',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'ncgsl',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'csgsl',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'psywscll',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'jas',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'sjsjfmk',  type: 'float', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'zygzld', type: 'string' },
               { name: 'czdzywt', type: 'string' },
               { name: 'mldzykn', type: 'string' },
               { name: 'xgdyjjy', type: 'string' },

               { name: 'statisticsuser', type: 'string' },
               { name: 'shuser', type: 'string' },
               { name: 'bzcslshdcqk', type: 'string' },
               { name: 'fxwtycljg', type: 'string' },
               { name: 'shuser', type: 'string' },
               { name: 'xysjcmxtjjsx', type: 'string' },
               { name: 'remark', type: 'string' },
    ],
})