//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.ICSAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class systemconfigs
    {
        public string code { get; set; }
        public string parentcode { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public string comment { get; set; }
        public Nullable<int> seqno { get; set; }
        public Nullable<int> isfolder { get; set; }
    }
}
