//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_PROJECT_W
    {
        public string BELONGXIAQUCODE { get; set; }
        public string OPERATEUSERNAME { get; set; }
        public Nullable<System.DateTime> OPERATEDATE { get; set; }
        public decimal ROW_ID { get; set; }
        public string YEARFLAG { get; set; }
        public string ROWGUID { get; set; }
        public Nullable<System.DateTime> HF_DATE { get; set; }
        public string WEBAPPLY_NOTE { get; set; }
        public string IS_SENDSMS { get; set; }
        public string PROJECT_MYD { get; set; }
        public string FWYZM { get; set; }
        public Nullable<decimal> SHOUFEISUM { get; set; }
        public string RECEIVEUSERNAME { get; set; }
        public Nullable<System.DateTime> RECEIVEDATE { get; set; }
        public string ACCEPTUSERGUID { get; set; }
        public Nullable<System.DateTime> BANWANDATE { get; set; }
        public string ACCEPTUSERNAME { get; set; }
        public Nullable<System.DateTime> ACCEPTUSERDATE { get; set; }
        public Nullable<System.DateTime> PROMISEENDDATE { get; set; }
        public Nullable<decimal> TASKTYPE { get; set; }
        public string BANJIEUSERGUID { get; set; }
        public string BANJIEUSERNAME { get; set; }
        public Nullable<decimal> BANJIERESULT { get; set; }
        public Nullable<System.DateTime> BANJIEDATE { get; set; }
        public Nullable<decimal> IS_CHARGE { get; set; }
        public string LEGAL { get; set; }
        public Nullable<decimal> HEBINGSHOULISHULIANG { get; set; }
        public Nullable<System.DateTime> FEEDATE { get; set; }
        public string CERTIFICATEUSERGUID { get; set; }
        public string CERTIFICATEUSERNAME { get; set; }
        public Nullable<System.DateTime> CERTIFICATEDATE { get; set; }
        public string CERTAWARDEGUID { get; set; }
        public string GUIDANGUSERGUID { get; set; }
        public string GUIDANGUSERNAME { get; set; }
        public Nullable<System.DateTime> GUIDANGDATE { get; set; }
        public string ORGWN { get; set; }
        public string BILLNO { get; set; }
        public Nullable<decimal> SPENDTIME { get; set; }
        public Nullable<decimal> SPARETIME { get; set; }
        public string APPLYERGUID { get; set; }
        public Nullable<decimal> APPLYWAY { get; set; }
        public Nullable<decimal> IS_PAUSE { get; set; }
        public string APPLYERTYPE { get; set; }
        public string CHARGE_WHEN { get; set; }
        public Nullable<decimal> IS_CHECK { get; set; }
        public Nullable<decimal> IS_FEE { get; set; }
        public Nullable<decimal> IS_GUIDANG { get; set; }
        public Nullable<decimal> IS_DELAY { get; set; }
        public Nullable<decimal> IS_GREEN { get; set; }
        public string ADDRESS { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public string PROJECTNAME { get; set; }
        public string TASKGUID { get; set; }
        public string TASKCASEGUID { get; set; }
        public string OUGUID { get; set; }
        public string ORG_ID { get; set; }
        public string WINDOWGUID { get; set; }
        public string WINDOWNAME { get; set; }
        public Nullable<decimal> CERTTYPE { get; set; }
        public string FLOWSN { get; set; }
        public string PVIGUID { get; set; }
        public string CONTACTPHONE { get; set; }
        public string XIANGMUBH { get; set; }
        public string CONTACTPERSON { get; set; }
        public string APPLYERNAME { get; set; }
        public string APPLYERUSERGUID { get; set; }
        public string CERTNUM { get; set; }
        public Nullable<System.DateTime> APPLYDATE { get; set; }
        public string CONTACTMOBILE { get; set; }
        public string CONTACTPOSTCODE { get; set; }
        public string CONTACTEMAIL { get; set; }
        public string CONTACTFAX { get; set; }
        public string RECEIVEUSERGUID { get; set; }
        public Nullable<decimal> IS_CERT { get; set; }
        public string CHECKUSERGUID { get; set; }
        public Nullable<decimal> PROMISE_DAY { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<System.DateTime> CHECKDATE { get; set; }
        public string CHECKUSERNAME { get; set; }
        public string ORGWORD { get; set; }
        public Nullable<decimal> ORGNUMBER { get; set; }
        public Nullable<decimal> TABLEID { get; set; }
        public Nullable<System.DateTime> BUBANDATE { get; set; }
        public Nullable<System.DateTime> YUSHENDATE { get; set; }
        public string ZIJIANXITONG_NUMBER { get; set; }
        public string APPLY_ATTACH_SIGN { get; set; }
        public string ATTACH_SIGN { get; set; }
        public string XIANGMUGUID { get; set; }
        public string XMADDRESS { get; set; }
        public string XMNAME { get; set; }
        public Nullable<decimal> IS_TEST { get; set; }
        public string ONLINEPAYORDERNO { get; set; }
        public string SUBAPPGUID { get; set; }
        public string WENSHUPDFGUID { get; set; }
        public string OFFICALPDFGUID { get; set; }
        public string CERTPDFGUID { get; set; }
        public string OFFICALDOCGUID { get; set; }
        public string BIGUID { get; set; }
        public string BUSINESSGUID { get; set; }
        public string RELATIONWORKITEMGUID { get; set; }
        public string PJ_OPNION { get; set; }
        public string PAYMENTNO { get; set; }
        public string ORDERNO { get; set; }
        public string PROJPWD { get; set; }
        public string PROJID { get; set; }
        public Nullable<System.DateTime> DATA_TIMESTAMP { get; set; }
        public string ZJSYNC { get; set; }
        public string SYNCROWGUID { get; set; }
        public string RESULT_CODE { get; set; }
    }
}
