//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDS_LAW_EXECUTOR
    {
        public string SOURCEKEY { get; set; }
        public string NAME { get; set; }
        public string DEPTKEY { get; set; }
        public string DEPTNAME { get; set; }
        public string TELEPHONE { get; set; }
        public string SEX { get; set; }
        public string BIRTHDAY { get; set; }
        public string USEABLE { get; set; }
        public string CREATETIME { get; set; }
        public string EXECUTORID { get; set; }
        public string TYPE { get; set; }
        public string AREA { get; set; }
        public string CREDENTIAL { get; set; }
        public string SDATE { get; set; }
        public string EDATE { get; set; }
        public string SORTID { get; set; }
        public string SYNCPAGENO { get; set; }
    }
}
