//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDS_STANDARD
    {
        public string STANDARDID { get; set; }
        public string LAWID { get; set; }
        public string POWERID { get; set; }
        public string POWERVERSION { get; set; }
        public string WFQX { get; set; }
        public string BREACHDERGEE { get; set; }
        public string BREACHGRADE { get; set; }
        public string SORTID { get; set; }
        public string CREATETIME { get; set; }
        public string FLAG { get; set; }
        public string DEPTKEY { get; set; }
        public string AREACODE { get; set; }
        public string DATAVERVISON { get; set; }
        public string EXTEND_1 { get; set; }
        public string EXTEND_2 { get; set; }
    }
}
