//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class qw_alarmcarmemorylocationdatas
    {
        public int id { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<System.DateTime> gpstime { get; set; }
        public Nullable<double> speed { get; set; }
        public Nullable<System.DateTime> alarmstrattime { get; set; }
        public Nullable<System.DateTime> alarmendtime { get; set; }
        public Nullable<int> alarmtype { get; set; }
        public Nullable<int> carid { get; set; }
        public Nullable<int> state { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> dealtime { get; set; }
        public Nullable<int> dealuserid { get; set; }
        public Nullable<int> isallege { get; set; }
        public string allegereason { get; set; }
        public Nullable<System.DateTime> allegetime { get; set; }
        public Nullable<int> appeals { get; set; }
    }
}
