//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXXZ.ZHCG.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesORCL : DbContext
    {
        public EntitiesORCL()
            : base("name=EntitiesORCL")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AUDIT_PROJECT_W> AUDIT_PROJECT_W { get; set; }
        public DbSet<FDS_LAW> FDS_LAW { get; set; }
        public DbSet<FDS_LAW_EXECUTOR> FDS_LAW_EXECUTOR { get; set; }
        public DbSet<FDS_POWER> FDS_POWER { get; set; }
        public DbSet<FDS_STANDARD> FDS_STANDARD { get; set; }
        public DbSet<FDS_STANDARD_PUNISH> FDS_STANDARD_PUNISH { get; set; }
        public DbSet<WORKFLOW_WORKITEM_HISTORY_W> WORKFLOW_WORKITEM_HISTORY_W { get; set; }
        public DbSet<WORKFLOW_WORKITEM_W> WORKFLOW_WORKITEM_W { get; set; }
    }
}
