Ext.define('TianZun.model.reportcenter.AddUp.AddUplawInWaterModel', {
    extend: 'Ext.data.Model',
    idProperty: 'taskId',
    fields: [
               { name: 'month', type: 'string' },
               { name: 'cdzfry', type: 'int', convert: function (value) { return value == null ? 0 : value } },
               { name: 'cdzfcl', type: 'int', convert: function (value) { return value == null ? 0 : value } },
               { name: 'kzzfxccs',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'zlxqzgtzs',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'fxsswt',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'wczgsswt',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'jsys',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'jcfx',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'tsjb',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'zlas',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'jsfaxhdjzw',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'hdfqw',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'pslj',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'ncgsl',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'csgsl',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'psywscll',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'jas',  type: 'int', convert: function (value) { return value == null ? 0 :value } }, 
               { name: 'sjsjfmk',  type: 'float', convert: function (value) { return value == null ? 0 :value } }, 
    ],
})